Repository thoth-station/image-pusher, pull requests merged in 2020-08, with the labels that each got.

#4 Automatic update of dependency thoth-common from 0.15.0 to 0.16.1
  Pipfile.lock
Labels: approved, bot, size/M

#5 Add type annotations and reformat using black
  app.py
Labels: size/M

#6 Use logger from thoth namespace
  app.py
Labels: size/XS

#9 Add missing import for the exception class raised on error
  app.py
Labels: size/XS

#7 Remove template files
  template/__init__.py
  template/version.py
Labels: size/S

#8 Maintain version string and print it to logs
  app.py
Labels: size/XS

#10 Raise on any error observed during image push
  app.py
Labels: size/XS

#11 Turn positional arguments into options to easily use them workflows
  README.md
  README.rst
  app.py
Labels: size/L
